enhances makefile
adds checksum for fetch dependencies

discovers necessary commands

fixes error when script get_container_id not found

diff --git a/build/run_image.template b/build/run_image.template
--- a/build/run_image.template
+++ b/build/run_image.template
@@ -2,12 +2,17 @@
 
 set -e
 
-PROJECT_ROOT="${PROJECT_ROOT:-%PROJECT_ROOT%}"
-
 DOCKER="${DOCKER:-%DOCKER%}"
 IMAGE="${IMAGE:-%IMAGE%}"
 NETWORK="${NETWORK:-host}"
-HOST_CONTAINER="${HOST_CONTAINER:-"$("$PROJECT_ROOT/build/get_container_id.sh")"}" || true
+PROJECT_ROOT="${PROJECT_ROOT:-%PROJECT_ROOT%}"
+CONTAINER_ID_CMD="$PROJECT_ROOT/build/get_container_id.sh"
+
+if command -v "$CONTAINER_ID_CMD" 2>&1 1>/dev/null; then
+  HOST_CONTAINER="${HOST_CONTAINER:-"$("$CONTAINER_ID_CMD")"}" || true
+else
+  echo "warning:$0: failed to discover host environment" 1>&2
+fi
 
 # shellcheck disable=SC2162
 read -a ADDITIONAL_RUNFLAGS <<< "$RUNFLAGS"
